// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCshtl0BLhg3H0Ot6eTDfZZRanteKJSjGI',
    appId: '1:1062021337714:web:4b059d064d641f501028eb',
    messagingSenderId: '1062021337714',
    projectId: 'prak-10-c3b34',
    authDomain: 'prak-10-c3b34.firebaseapp.com',
    storageBucket: 'prak-10-c3b34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY9YLii-VpdWScR6bYkMTna1uCbJR9zr4',
    appId: '1:1062021337714:android:f73d3752dfa9117e1028eb',
    messagingSenderId: '1062021337714',
    projectId: 'prak-10-c3b34',
    storageBucket: 'prak-10-c3b34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCULucGHDejHowHAvQuK1R_axQYpa794c4',
    appId: '1:1062021337714:ios:e2357a4c47df98861028eb',
    messagingSenderId: '1062021337714',
    projectId: 'prak-10-c3b34',
    storageBucket: 'prak-10-c3b34.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCULucGHDejHowHAvQuK1R_axQYpa794c4',
    appId: '1:1062021337714:ios:e2357a4c47df98861028eb',
    messagingSenderId: '1062021337714',
    projectId: 'prak-10-c3b34',
    storageBucket: 'prak-10-c3b34.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
